//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TWWHeapVisualizer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TWWHeapVisualizer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ActorDatabase {
            get {
                object obj = ResourceManager.GetObject("ActorDatabase", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BWDG               : 35D40
        ///BGN3               : 100B4
        ///BRIDGE             :  D0F8
        ///BGN                :  CC94
        ///Menu_Cloth         :  929C
        ///BTD                :  6E94
        ///BDK                :  63CC
        ///PLAYER             :  4C28
        ///SS                 :  4218
        ///BWD                :  3C54
        ///NPC_MD             :  32C0
        ///DAIOCTA            :  31C8
        ///BGN2               :  30DC
        ///MO2                :  3038
        ///METER              :  302C
        ///BST                :  2FE8
        ///MANT               :  283C
        ///HIMO2              :  2738
        ///ST       [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ActorInstanceSizes {
            get {
                return ResourceManager.GetString("ActorInstanceSizes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DownwardIcon {
            get {
                object obj = ResourceManager.GetObject("DownwardIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ExportStructureDataToCSV {
            get {
                object obj = ResourceManager.GetObject("ExportStructureDataToCSV", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ForwardIcon {
            get {
                object obj = ResourceManager.GetObject("ForwardIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ghidra_datatypes {
            get {
                object obj = ResourceManager.GetObject("ghidra_datatypes", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap green_arrow {
            get {
                object obj = ResourceManager.GetObject("green_arrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap green_arrow_hover {
            get {
                object obj = ResourceManager.GetObject("green_arrow_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProcName,ProcValue,StructName,FileName,Guess
        ///PROC_ACORN_LEAF,299,daAleaf_c,d_a_acorn_leaf.cpp,True
        ///PROC_AGB,437,daAgb_c,d_a_agb.cpp,False
        ///PROC_AGBSW0,438,daAgbsw0_c,d_a_agbsw0.cpp,False
        ///PROC_ALLDIE,22,daAlldie_c,d_a_alldie.cpp,False
        ///PROC_AM,203,am_class,d_a_am.cpp,False
        ///PROC_AM2,204,am2_class,d_a_am2.cpp,False
        ///PROC_AMI_PROP,96,daAmiProp_c,d_a_amiprop.cpp,True
        ///PROC_ANDSW0,309,andsw0_class,d_a_andsw0.cpp,False
        ///PROC_ANDSW2,310,daAndsw2_c,d_a_andsw2.cpp,False
        ///PROC_ARROW,478,daArrow_c,d_a_arrow.cpp,Fal [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string proc_name_structs {
            get {
                return ResourceManager.GetString("proc_name_structs", resourceCulture);
            }
        }
    }
}
